<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SystemDefinition [
<!ELEMENT SystemDefinition ( systemModel )>
<!ATTLIST SystemDefinition
  name CDATA #REQUIRED
  schema CDATA #REQUIRED
>
<!-- all paths are relative to the environment variable specified by the root attribute, or SOURCEROOT if not.  -->

<!-- System Model Section of DTD -->
<!ELEMENT systemModel (layer+)>

<!ELEMENT layer (block* | collection*)*>
<!-- Kernel Services, Base Services, OS Services, Etc -->
<!ATTLIST layer
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
  levels NMTOKENS #IMPLIED
  span CDATA #IMPLIED
>

<!ELEMENT block (subblock* | collection*)*>
 <!-- Generic OS services, Comms Services, etc -->
<!ATTLIST block
  levels NMTOKENS #IMPLIED
  span CDATA #IMPLIED
  level NMTOKEN #IMPLIED
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
>

<!ELEMENT subblock (collection)*>
<!-- Cellular Baseband Services, Networking Services, etc -->
<!ATTLIST subblock
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
>

<!ELEMENT collection (component)*>
<!-- Screen Driver, Content Handling, etc -->
<!ATTLIST collection
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
  level NMTOKEN #IMPLIED
>

<!ELEMENT component (unit)*>
<!-- contains units or is a  package or prebuilt -->
<!ATTLIST component
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
  deprecated CDATA #IMPLIED
  introduced CDATA #IMPLIED
  contract CDATA #IMPLIED
  plugin (Y|N) "N"
  filter CDATA #IMPLIED
  class NMTOKENS #IMPLIED
  supports CDATA #IMPLIED
  purpose ( optional | mandatory | development ) "optional"
>

<!ELEMENT unit EMPTY >
<!-- must be buildable (bld.inf) -->
<!-- bldFile  may someday be removed in favour of mrp -->
<!ATTLIST unit
  mrp CDATA #IMPLIED
  filter CDATA #IMPLIED
  bldFile CDATA #IMPLIED
  root CDATA #IMPLIED
  version NMTOKEN #IMPLIED
  prebuilt NMTOKEN #IMPLIED
  late (Y|N) #IMPLIED
  priority CDATA #IMPLIED
>
]>
<SystemDefinition name="Symbian^3" schema="2.0.1">
  <systemModel>
    <layer name="mw" long-name="Middleware" levels="generic specific">
      <block name="mmuifw" level="specific" long-name="Multimedia UI Framework" levels="mgr mdl util ui">
        <collection name="mmuifw_info" long-name="Multimedia UI Framework Info" level="ui">
          <component name="mmuifw_plat" filter="s60" long-name="Multimedia UI Framework Platform Interfaces" class="api">
            <unit bldFile="/sf/mw/mmuifw/mmuifw_plat/group"/>
          </component>
          <component name="mmuifw_build" filter="s60" long-name="Multimedia UI Framework Build">
            <!-- Move exports into other componetns or remove all #includes and make this a ROM component -->
            <unit bldFile="/sf/mw/mmuifw/group"/>
          </component>
        </collection>
        <collection name="osncore" long-name="OS Neutral Library Core" level="util">
          <!-- collection is really a component. Move down a directory -->
          <component name="osncore_build" filter="s60" long-name="OSN Core Build">
            <unit bldFile="/sf/mw/mmuifw/osncore/group"/>
          </component>
        </collection>
        <collection name="alfwidgetutils" long-name="Accelerated LAF Widget Utils" level="ui">
          <!-- collection is really a component. Move down a directory -->
          <component name="alfwidgetutils_build" filter="s60" long-name="ALF Widget Utils">
            <unit bldFile="/sf/mw/mmuifw/alfwidgetutils/group"/>
          </component>
        </collection>
        <collection name="resourcepool" long-name="Resource Pool" level="util">
          <!-- collection is really a component. Move down a directory -->
          <component name="alfresourcepool" filter="s60" long-name="ALF Resource Pool">
            <unit bldFile="/sf/mw/mmuifw/resourcepool/group"/>
          </component>
        </collection>
        <collection name="widgetmodel" long-name="Widget Model" level="mdl">
          <!-- collection is really a component. Move down a directory -->
          <component name="widgetmodel_build" filter="s60" long-name="Widget Model Build">
            <unit bldFile="/sf/mw/mmuifw/widgetmodel/group"/>
          </component>
        </collection>
        <collection name="mulwidgets" long-name="MUL Widgets" level="ui">
          <!-- should spell out MUL in the collection name -->
          <component name="mullogging" filter="s60" long-name="MUL Logging">
            <unit bldFile="/sf/mw/mmuifw/mulwidgets/mullogging/group"/>
          </component>
          <component name="muldatamodel" filter="s60" long-name="MUL Data Model">
            <unit bldFile="/sf/mw/mmuifw/mulwidgets/muldatamodel/group"/>
          </component>
          <component name="mulwidgets_common" filter="s60" long-name="MUL Common Utils">
            <unit bldFile="/sf/mw/mmuifw/mulwidgets/common/group"/>
          </component>
          <component name="gesturehelper" filter="s60" long-name="Gesture Helper">
            <unit bldFile="/sf/mw/mmuifw/mulwidgets/gesturehelper/group"/>
          </component>
          <component name="mulcoverflowwidget" filter="s60" long-name="MUL CoverFlow Widget">
            <unit bldFile="/sf/mw/mmuifw/mulwidgets/mulcoverflowwidget/group"/>
          </component>
          <component name="mulsliderwidget" filter="s60" long-name="MUL Slider Widget">
            <unit bldFile="/sf/mw/mmuifw/mulwidgets/mulsliderwidget/group"/>
          </component>
          <component name="alfviewwidget" filter="s60" long-name="ALF View Widget">
            <unit bldFile="/sf/mw/mmuifw/mulwidgets/alfviewwidget/group"/>
          </component>
          <component name="alfcontainerwidget" filter="s60" long-name="ALF Container Widget">
            <unit bldFile="/sf/mw/mmuifw/mulwidgets/alfcontainerwidget/group"/>
          </component>
          <component name="alfscrollbarwidget" filter="s60" long-name="ALF Scrollbar Widget">
            <unit bldFile="/sf/mw/mmuifw/mulwidgets/alfscrollbarwidget/group"/>
          </component>
        </collection>
      </block>
    </layer>
  </systemModel>
</SystemDefinition>
