<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SystemDefinition [
 <!ELEMENT SystemDefinition (systemModel)>
 <!ATTLIST SystemDefinition
  name CDATA #REQUIRED
  schema CDATA #REQUIRED>
 <!ELEMENT systemModel (layer+)>
 <!ELEMENT layer (block*|collection*)*>
 <!ATTLIST layer
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
  levels NMTOKENS #IMPLIED
  span CDATA #IMPLIED>
 <!ELEMENT block (subblock*|collection*)*>
 <!ATTLIST block
  levels NMTOKENS #IMPLIED
  span CDATA #IMPLIED
  level NMTOKEN #IMPLIED
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED>
 <!ELEMENT subblock (collection)*>
 <!ATTLIST subblock
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED>
 <!ELEMENT collection (component)*>
 <!ATTLIST collection
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
  level NMTOKEN #IMPLIED>
 <!ELEMENT component (unit)*>
 <!ATTLIST component
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
  deprecated CDATA #IMPLIED
  introduced CDATA #IMPLIED
  contract CDATA #IMPLIED
  plugin (Y|N) 'N'
  filter CDATA #IMPLIED
  class NMTOKENS #IMPLIED
  supports CDATA #IMPLIED
  purpose (optional|mandatory|development) 'optional'>
 <!ELEMENT unit EMPTY>
 <!ATTLIST unit
  mrp CDATA #IMPLIED
  filter CDATA #IMPLIED
  bldFile CDATA #IMPLIED
  root CDATA #IMPLIED
  version NMTOKEN #IMPLIED
  prebuilt NMTOKEN #IMPLIED
  late (Y|N) #IMPLIED
  priority CDATA #IMPLIED>
]>
<SystemDefinition name="Symbian^4" schema="2.0.1">
<systemModel>
<layer name="mw" long-name="Middleware" levels="generic specific">
<block name="hapticsservices" level="generic" long-name="Haptics Services" levels="fw server api">
<collection name="hapticsservices_plat" long-name="Haptics Services Platform Interfaces" level="api">
<component name="tacticon_api" long-name="Tacticon API" introduced="^1" filter="s60" class="api">
<unit bldFile="/sf/mw/hapticsservices/hapticsservices_plat/tacticon_api/group"/>
</component>
<component name="tactile_feedback_core_api" long-name="Tactile Feedback Core API" introduced="^1" filter="s60" class="api">
<unit bldFile="/sf/mw/hapticsservices/hapticsservices_plat/tactile_feedback_core_api/group"/>
</component>
<component name="tactile_feedback_server_api" long-name="Tactile Feedback Server API" introduced="^1" filter="s60" class="api">
<unit bldFile="/sf/mw/hapticsservices/hapticsservices_plat/tactile_feedback_server_api/group"/>
</component>
</collection>
<collection name="hapticsservices_pub" long-name="Haptics Services Public Interfaces" level="api">
<component name="tactile_feedback_client_api" long-name="Tactile Feedback Client API" introduced="^1" filter="s60" class="api">
<unit bldFile="/sf/mw/hapticsservices/hapticsservices_pub/tactile_feedback_client_api/group"/>
</component>
</collection>
<collection name="tacticonserver" long-name="Tacticon Server" level="server">
<!-- collection is really a component. Move down a directory  -->
<component name="tacticonserver_build" filter="s60" long-name="Tacticon Server Build" introduced="^3">
<unit bldFile="/sf/mw/hapticsservices/tacticonserver/group"/>
<!-- clients and servers are suauly the same component. Consider moving pluign to a separate component if needed -->
</component>
</collection>
<collection name="tactilefeedback" long-name="Tactile Feedback" level="fw">
<component name="tactilearearegistry" filter="s60" long-name="Tactile Area Registry" introduced="^1">
<unit bldFile="/sf/mw/hapticsservices/tactilefeedback/tactilearearegistry/group"/>
</component>
<component name="tactilefeedbackresolver" filter="s60" long-name="Tactile Feedback Resolver" introduced="^1">
<unit bldFile="/sf/mw/hapticsservices/tactilefeedback/tactilefeedbackresolver/group"/>
</component>
<component name="tactileclickplugin" filter="s60" long-name="Tactile Click Plugin" introduced="^1" plugin="Y">
<unit bldFile="/sf/mw/hapticsservices/tactilefeedback/tactileclickplugin/group"/>
</component>
<component name="tactilefeedbackclient" filter="s60" long-name="Tactile Feedback Client" introduced="^1">
<unit bldFile="/sf/mw/hapticsservices/tactilefeedback/tactilefeedbackclient/group"/>
</component>
<component name="tactileactionplugin" filter="s60" long-name="Tactile Action Plugin" introduced="^1" plugin="Y">
<unit bldFile="/sf/mw/hapticsservices/tactilefeedback/tactileactionplugin/group"/>
</component>
<component name="tactilefeedback_build" filter="s60" long-name="Tactile Feedback Build" introduced="^1">
<!-- consider moving IBY to one fo the above components -->
<unit bldFile="/sf/mw/hapticsservices/tactilefeedback/group"/>
</component>
</collection>
</block>
</layer>
</systemModel>
</SystemDefinition>