<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SystemDefinition [
 <!ELEMENT SystemDefinition (systemModel)>
 <!ATTLIST SystemDefinition
  name CDATA #REQUIRED
  schema CDATA #REQUIRED>
 <!ELEMENT systemModel (layer+)>
 <!ELEMENT layer (block*|collection*)*>
 <!ATTLIST layer
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
  levels NMTOKENS #IMPLIED
  span CDATA #IMPLIED>
 <!ELEMENT block (subblock*|collection*)*>
 <!ATTLIST block
  levels NMTOKENS #IMPLIED
  span CDATA #IMPLIED
  level NMTOKEN #IMPLIED
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED>
 <!ELEMENT subblock (collection)*>
 <!ATTLIST subblock
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED>
 <!ELEMENT collection (component)*>
 <!ATTLIST collection
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
  level NMTOKEN #IMPLIED>
 <!ELEMENT component (unit)*>
 <!ATTLIST component
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
  deprecated CDATA #IMPLIED
  introduced CDATA #IMPLIED
  contract CDATA #IMPLIED
  plugin (Y|N) 'N'
  filter CDATA #IMPLIED
  class NMTOKENS #IMPLIED
  supports CDATA #IMPLIED
  purpose (optional|mandatory|development) 'optional'>
 <!ELEMENT unit EMPTY>
 <!ATTLIST unit
  mrp CDATA #IMPLIED
  filter CDATA #IMPLIED
  bldFile CDATA #IMPLIED
  root CDATA #IMPLIED
  version NMTOKEN #IMPLIED
  prebuilt NMTOKEN #IMPLIED
  late (Y|N) #IMPLIED
  priority CDATA #IMPLIED>
]>
<SystemDefinition name="Symbian^3" schema="2.0.1">
 <systemModel>
  <layer name="mw" long-name="Middleware" levels="generic specific">
   <block name="classicui" level="generic" long-name="Classic UI" levels="base support server generic specific">
<collection name="classicui_plat" long-name="Classic UI Platform Interfaces" level="specific">
<component name="personalisation_framework_api" long-name="Personalisation Framework API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/personalisation_framework_api/group" filter="!test"/>
</component>
<component name="signal_pane_api" long-name="Signal Pane API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/signal_pane_api/group" filter="!test"/>
</component>
<component name="japanese_reading_api" long-name="Japanese Reading API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/japanese_reading_api/group" filter="!test"/>
</component>
<component name="global_popup_priority_controller_api" long-name="Global Popup Priority Controller API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/global_popup_priority_controller_api/group" filter="!test"/>
</component>
<component name="item_finder_api" long-name="Item Finder API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/item_finder_api/group" filter="!test"/>
</component>
<component name="avkon_fonts_api" long-name="Avkon Fonts API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/avkon_fonts_api/group" filter="!test"/>
</component>
<component name="extended_utilities_api" long-name="Extended Utilities API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/extended_utilities_api/group" filter="!test"/>
</component>
<component name="personalisation_plugin_api" long-name="Personalisation Plugin API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/personalisation_plugin_api/group"/>
</component>
<component name="extended_aiw_criteria_api" long-name="Extended AIW Criteria API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/extended_aiw_criteria_api/group" filter="!test"/>
</component>
<component name="personalisation_application_api" long-name="Personalisation Application API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/personalisation_application_api/group"/>
</component>
<component name="volume_popup_api" long-name="Volume Popup API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/volume_popup_api/group" filter="!test"/>
</component>
<component name="avkon_secondary_display_support_api" long-name="AVKON Secondary Display Support API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/avkon_secondary_display_support_api/group" filter="!test"/>
</component>
<component name="extended_setting_pages_api" long-name="Extended Setting Pages API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/extended_setting_pages_api/group" filter="!test"/>
</component>
<component name="extended_lists_api" long-name="Extended Lists API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/extended_lists_api/group" filter="!test"/>
</component>
<component name="input_block_api" long-name="Input Block API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/input_block_api/group" filter="!test"/>
</component>
<component name="avkon_ui_server_api" long-name="AVKON UI Server API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/avkon_ui_server_api/group" filter="!test"/>
</component>
<component name="number_grouping_api" long-name="Number Grouping API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/number_grouping_api/group" filter="!test"/>
</component>
<component name="extended_status_pane_api" long-name="Extended Status Pane API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/extended_status_pane_api/group" filter="!test"/>
</component>
<component name="extended_notifiers_api" long-name="Extended Notifiers API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/extended_notifiers_api/group" filter="!test"/>
</component>
<component name="task_list_api" long-name="Task List API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/task_list_api/group" filter="!test"/>
</component>
<component name="personalisation_slide_show_dialog_api" long-name="Personalisation Slide Show Dialog API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/personalisation_slide_show_dialog_api/group"/>
</component>
<component name="key_event_utilities_api" long-name="Key Event Utilities API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/key_event_utilities_api/group"/>
</component>
<component name="emergency_call_support_api" long-name="Emergency Call Support API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/emergency_call_support_api/group" filter="!test"/>
</component>
<component name="extended_dialogs_api" long-name="Extended Dialogs API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/extended_dialogs_api/group"/>
</component>
<component name="legacy_ui_framework_headers_api" long-name="Legacy UI Framework Headers API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/legacy_ui_framework_headers_api/group"/>
</component>
<component name="extended_editors_api" long-name="Extended Editors API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/extended_editors_api/group" filter="!test"/>
</component>
<component name="alarm_api" long-name="Alarm API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/alarm_api/group" filter="!test"/>
</component>
<component name="aiw_service_interface_base_api" long-name="AIW Service Interface Base API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/aiw_service_interface_base_api/group" filter="!test"/>
</component>
<component name="list_effects_api" long-name="List Effects API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/list_effects_api/group" filter="!test"/>
</component>
<component name="find_item_ui_api" long-name="Find Item UI API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/find_item_ui_api/group" filter="!test"/>
</component>
<component name="server_application_services_api" long-name="Server Application Services API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/server_application_services_api/group" filter="!test"/>
</component>
<component name="common_ui_settings_api" long-name="Common UI Settings API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/common_ui_settings_api/group"/>
</component>
<component name="aiw_service_interface_menu_api" long-name="AIW Service Interface Menu API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/aiw_service_interface_menu_api/group" filter="!test"/>
</component>
<component name="eikon_server_extension_client_api" long-name="EIKON Server Extension Client API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/eikon_server_extension_client_api/group" filter="!test"/>
</component>
<component name="skinnable_clock_api" long-name="Skinnable Clock API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/skinnable_clock_api/group" filter="!test"/>
</component>
<component name="battery_pane_api" long-name="Battery Pane API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/battery_pane_api/group" filter="!test"/>
</component>
<component name="fep_document_navigation_api" long-name="FEP Document Navigation API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/fep_document_navigation_api/group"/>
</component>
<component name="personalisation_localised_texts_api" long-name="Personalisation Localised Texts API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/personalisation_localised_texts_api/group"/>
</component>
<component name="memory_card_ui_api" long-name="Memory Card UI API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/memory_card_ui_api/group" filter="!test"/>
</component>
<component name="avkon_status_api" long-name="AVKON Status API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/avkon_status_api/group"/>
</component>
<component name="application_switching_api" long-name="Application Switching API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/application_switching_api/group" filter="!test"/>
</component>
<component name="avkon_localised_texts_api" long-name="AVKON Localised Texts API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/avkon_localised_texts_api/group"/>
</component>
<component name="avkon_secondary_display_api" long-name="AVKON Secondary Display API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/avkon_secondary_display_api/group"/>
</component>
<component name="extended_animation_api" long-name="Extended Animation API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/extended_animation_api/group" filter="!test"/>
</component>
<component name="extended_notes_api" long-name="Extended Notes API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/extended_notes_api/group" filter="!test"/>
</component>
<component name="screensaver_animation_plugin_definitions_api" long-name="Screensaver Animation Plugin Definitions API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/screensaver_animation_plugin_definitions_api/group"/>
</component>
<component name="text_scroller_api" long-name="Text Scroller API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/text_scroller_api/group" filter="!test"/>
</component>
<component name="custom_cursors_api" long-name="Custom Cursors API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/custom_cursors_api/group" filter="!test"/>
</component>
<component name="screensaver_settings_api" long-name="Screensaver Settings API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/screensaver_settings_api/group"/>
</component>
<component name="global_window_priorities_api" long-name="Global Window Priorities API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/global_window_priorities_api/group"/>
</component>
<component name="extended_indicators_api" long-name="Extended Indicators API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/extended_indicators_api/group" filter="!test"/>
</component>
<component name="special_character_table_api" long-name="Special Character Table API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/special_character_table_api/group" filter="!test"/>
</component>
<component name="avkon_settings_api" long-name="AVKON Settings API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/avkon_settings_api/group"/>
</component>
<component name="extended_sounds_api" long-name="Extended Sounds API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/extended_sounds_api/group"/>
</component>
<component name="themes_settings_api" long-name="Themes Settings API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/themes_settings_api/group"/>
</component>
<component name="media_shared_document_api" long-name="Media Shared Document API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/media_shared_document_api/group" filter="!test"/>
</component>
<component name="extended_queries_api" long-name="Extended Queries API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/extended_queries_api/group"/>
</component>
<component name="phone_number_text_utilities_api" long-name="Phone Number Text Utilities API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/phone_number_text_utilities_api/group" filter="!test"/>
</component>
<component name="screensaver_runtime_api" long-name="Screensaver Runtime API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/screensaver_runtime_api/group"/>
</component>
<component name="extended_scroller_api" long-name="Extended Scroller API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/extended_scroller_api/group"/>
</component>
<component name="key_rotator_api" long-name="Key Rotator API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/key_rotator_api/group" filter="!test"/>
</component>
<component name="extended_grids_api" long-name="Extended Grids API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/extended_grids_api/group" filter="!test"/>
</component>
<component name="generic_parameter_api" long-name="Generic Parameter API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/generic_parameter_api/group" filter="!test"/>
</component>
<component name="indicator_touch_observer_api" long-name="Indicator Touch Observer API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/indicator_touch_observer_api/group"/>
</component>
<component name="popup_form_api" long-name="Popup Form API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/popup_form_api/group" filter="!test"/>
</component>
<component name="stylus_activated_popup_api" long-name="Stylus Activated Pop-up API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/stylus_activated_popup_api/group" filter="!test"/>
</component>
<component name="indicator_plugin_api" long-name="Indicator Plugin API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/indicator_plugin_api/group" filter="!test"/>
</component>
<component name="layout_configuration_api" long-name="Layout Configuration API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/layout_configuration_api/group" filter="!test"/>
</component>
<component name="common_file_dialogs_filter_factory_api" long-name="Common File Dialogs Filter Factory API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/common_file_dialogs_filter_factory_api/group" filter="!test"/>
</component>
<component name="avkon_anim_dll_api" long-name="AVKON Anim DLL API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/avkon_anim_dll_api/group"/>
</component>
<component name="extended_initialization_api" long-name="Extended Initialization API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/extended_initialization_api/group" filter="!test"/>
</component>
<component name="long_tap_animation_api" long-name="Long Tap Animation API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/long_tap_animation_api/group" filter="!test"/>
</component>
<component name="extended_ui_framework_definitions_api" long-name="Extended UI Framework Definitions API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/extended_ui_framework_definitions_api/group"/>
</component>
<component name="extended_buttons_api" long-name="Extended Buttons API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/extended_buttons_api/group" filter="!test"/>
</component>
<component name="aiw_provider_utility_api" long-name="AIW Provider Utility API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/aiw_provider_utility_api/group" filter="!test"/>
</component>
<component name="transition_effect_parameters_api" long-name="Transition Effect Parameters API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/transition_effect_parameters_api/group" filter="!test"/>
</component>
<component name="extended_input_capabilities_api" long-name="Extended Input Capabilities API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/extended_input_capabilities_api/group" filter="!test"/>
</component>
<component name="uikon_status_api" long-name="UIKON Status API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/uikon_status_api/group"/>
</component>
<component name="transition_effect_utilities_api" long-name="Transition Effect Utilities API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/transition_effect_utilities_api/group" filter="!test"/>
</component>
<component name="pointer_event_modifier_api" long-name="Pointer Event Modifier API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/pointer_event_modifier_api/group" filter="!test"/>
</component>
<component name="avkon_testability_api" long-name="AVKON Testability API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/avkon_testability_api/group"/>
</component>
<component name="ganes_api" long-name="Ganes API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/ganes_api/group"/>
</component>
<component name="ode_api" long-name="Ode API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/ode_api/group"/>
</component>
<component name="physics_api" long-name="Physics API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/physics_api/group"/>
</component>
<component name="touch_pane_api" long-name="Touch Pane API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/touch_pane_api/group" filter="!test"/>
</component>
<component name="touch_pane_observer_api" long-name="Touch Pane Observer API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/touch_pane_observer_api/group"/>
</component>
<component name="alternate_fs_api" long-name="Alternate FS API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/alternate_fs_api/group"/>
</component>
<component name="discreet_popup_api" long-name="Discreet Popup API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/discreet_popup_api/group"/>
</component>
<component name="touch_gesture_framework_api" long-name="Touch Gesture Framework API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/touch_gesture_framework_api/group"/>
<!-- should this be commented out? -->
<!--<unit bldFile="classicui_plat/touch_gesture_framework_api/tsrc/group" filter="test,api_test"/> -->
</component>
<component name="extended_options_menu_api" long-name="Extended Options Menu API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_plat/extended_options_menu_api/group" filter="!test"/>
</component>
</collection>
<collection name="classicui_pub" long-name="Classic UI Public Interfaces" level="specific">
<component name="input_frame_api" long-name="Input Frame API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/input_frame_api/group" filter="!test"/>
</component>
<component name="window_server_event_observer_api" long-name="Window Server Event Observer API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/window_server_event_observer_api/group" filter="!test"/>
</component>
<component name="application_framework_api" long-name="Application Framework API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/application_framework_api/group" filter="!test"/>
</component>
<component name="scroller_api" long-name="Scroller API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/scroller_api/group" filter="!test"/>
</component>
<component name="ui_framework_utilities_api" long-name="UI Framework Utilities API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/ui_framework_utilities_api/group" filter="!test"/>
</component>
<component name="ui_framework_definitions_api" long-name="UI Framework Definitions API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/ui_framework_definitions_api/group" filter="!test"/>
</component>
<component name="buttons_api" long-name="Buttons API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/buttons_api/group" filter="!test"/>
</component>
<component name="queries_api" long-name="Queries API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/queries_api/group" filter="!test"/>
</component>
<component name="aiw_generic_parameter_api" long-name="AIW Generic Parameter API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/aiw_generic_parameter_api/group" filter="!test"/>
</component>
<component name="editors_api" long-name="Editors API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/editors_api/group" filter="!test"/>
</component>
<component name="common_file_dialogs_api" long-name="Common File Dialogs API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/common_file_dialogs_api/group" filter="!test"/>
</component>
<component name="dialog_shutter_api" long-name="Dialog Shutter API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/dialog_shutter_api/group" filter="!test"/>
</component>
<component name="fonts_api" long-name="Fonts API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/fonts_api/group" filter="!test"/>
</component>
<component name="screen_clearer_api" long-name="Screen Clearer API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/screen_clearer_api/group" filter="!test"/>
</component>
<component name="notifiers_api" long-name="Notifiers API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/notifiers_api/group" filter="!test"/>
</component>
<component name="notes_api" long-name="Notes API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/notes_api/group" filter="!test"/>
</component>
<component name="screen_saver_api" long-name="Screen Saver API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/screen_saver_api/group" filter="!test"/>
</component>
<component name="status_pane_api" long-name="Status Pane API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/status_pane_api/group" filter="!test"/>
</component>
<component name="base_controls_api" long-name="Base Controls API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/base_controls_api/group" filter="!test"/>
</component>
<component name="grids_api" long-name="Grids API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/grids_api/group" filter="!test"/>
</component>
<component name="context_pane_api" long-name="Context Pane API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/context_pane_api/group" filter="!test"/>
</component>
<component name="lists_api" long-name="Lists API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/lists_api/group" filter="!test"/>
</component>
<component name="popups_api" long-name="Popups API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/popups_api/group" filter="!test"/>
</component>
<component name="misc_controls_api" long-name="Misc Controls API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/misc_controls_api/group" filter="!test"/>
</component>
<component name="keylock_api" long-name="Keylock API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/keylock_api/group" filter="!test"/>
</component>
<component name="options_menu_api" long-name="Options Menu API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/options_menu_api/group" filter="!test"/>
</component>
<component name="hierarchical_lists_api" long-name="Hierarchical Lists API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/hierarchical_lists_api/group" filter="!test"/>
</component>
<component name="navigation_pane_api" long-name="Navigation Pane API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/navigation_pane_api/group" filter="!test"/>
</component>
<component name="tabs_api" long-name="Tabs API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/tabs_api/group" filter="!test"/>
</component>
<component name="title_pane_touch_observer_api" long-name="Title Pane Touch Observer API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/title_pane_touch_observer_api/group"/>
</component>
<component name="choice_list_api" long-name="Choice List API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/choice_list_api/group" filter="!test"/>
</component>
<component name="info_popup_note_api" long-name="Info Popup Note API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/info_popup_note_api/group" filter="!test"/>
</component>
<component name="setting_pages_api" long-name="Setting Pages API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/setting_pages_api/group" filter="!test"/>
</component>
<component name="screen_mode_api" long-name="Screen Mode API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/screen_mode_api/group" filter="!test"/>
</component>
<component name="indicators_api" long-name="Indicators API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/indicators_api/group" filter="!test"/>
</component>
<component name="error_ui_api" long-name="Error UI API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/error_ui_api/group" filter="!test"/>
</component>
<component name="animation_api" long-name="Animation API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/animation_api/group" filter="!test"/>
</component>
<component name="searchfield_api" long-name="Searchfield API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/searchfield_api/group" filter="!test"/>
</component>
<component name="labels_api" long-name="Labels API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/labels_api/group" filter="!test"/>
</component>
<component name="hotkeys_api" long-name="Hotkeys API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/hotkeys_api/group" filter="!test"/>
</component>
<component name="initialization_api" long-name="Initialization API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/initialization_api/group" filter="!test"/>
</component>
<component name="volume_control_api" long-name="Volume Control API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/volume_control_api/group" filter="!test"/>
</component>
<component name="title_pane_api" long-name="Title Pane API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/title_pane_api/group" filter="!test"/>
</component>
<component name="sounds_api" long-name="Sounds API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/sounds_api/group" filter="!test"/>
</component>
<component name="aiw_service_handler_api" long-name="AIW Service Handler API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/aiw_service_handler_api/group" filter="!test"/>
</component>
<component name="aiw_criteria_api" long-name="AIW Criteria API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/aiw_criteria_api/group" filter="!test"/>
</component>
<component name="touch_ui_utilities_api" long-name="Touch UI Utilities API" filter="s60" class="api">
<unit bldFile="/sf/mw/classicui/classicui_pub/touch_ui_utilities_api/group" filter="!test"/>
</component>
<component name="generic_button_api" long-name="Generic Button API" filter="s60" class="api">