<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SystemDefinition [
 <!ELEMENT SystemDefinition (systemModel)>
 <!ATTLIST SystemDefinition
  name CDATA #REQUIRED
  schema CDATA #REQUIRED>
 <!ELEMENT systemModel (layer+)>
 <!ELEMENT layer (block*|collection*)*>
 <!ATTLIST layer
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
  levels NMTOKENS #IMPLIED
  span CDATA #IMPLIED>
 <!ELEMENT block (subblock*|collection*)*>
 <!ATTLIST block
  levels NMTOKENS #IMPLIED
  span CDATA #IMPLIED
  level NMTOKEN #IMPLIED
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED>
 <!ELEMENT subblock (collection)*>
 <!ATTLIST subblock
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED>
 <!ELEMENT collection (component)*>
 <!ATTLIST collection
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
  level NMTOKEN #IMPLIED>
 <!ELEMENT component (unit)*>
 <!ATTLIST component
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
  deprecated CDATA #IMPLIED
  introduced CDATA #IMPLIED
  contract CDATA #IMPLIED
  plugin (Y|N) 'N'
  filter CDATA #IMPLIED
  class NMTOKENS #IMPLIED
  supports CDATA #IMPLIED
  purpose (optional|mandatory|development) 'optional'>
 <!ELEMENT unit EMPTY>
 <!ATTLIST unit
  mrp CDATA #IMPLIED
  filter CDATA #IMPLIED
  bldFile CDATA #IMPLIED
  root CDATA #IMPLIED
  version NMTOKEN #IMPLIED
  prebuilt NMTOKEN #IMPLIED
  late (Y|N) #IMPLIED
  priority CDATA #IMPLIED>
]>
<SystemDefinition name="Symbian^3" schema="2.0.1">
 <systemModel>
  <layer name="app" long-name="Applications" levels="services apps">
   <block name="phone" level="apps" span="2" long-name="Phone Apps" levels="engine plugin ui app">
<collection name="phone_plat" long-name="Phone Apps Platform Interfaces" level="app">
<component name="ringing_tone_3d_enabler_api" long-name="3D Ringing Tone Enabler API" filter="s60" class="api">
<unit bldFile="/sf/app/phone/phone_plat/3d_ringing_tone_enabler_api/group"/>
</component>
<component name="telephony_comms_information_api" long-name="Telephony Comms Information API" filter="s60" class="api">
<unit bldFile="/sf/app/phone/phone_plat/telephony_comms_information_api/group"/>
</component>
<component name="telephony_information_api" long-name="Telephony Information API" filter="s60" class="api">
<unit bldFile="/sf/app/phone/phone_plat/telephony_information_api/group"/>
</component>
<component name="telephony_device_mode_api" long-name="Telephony Device Mode API" filter="s60" class="api">
<unit bldFile="/sf/app/phone/phone_plat/telephony_device_mode_api/group"/>
</component>
<component name="telephony_remote_party_information_api" long-name="Telephony Remote Party Information API" filter="s60" class="api">
<unit bldFile="/sf/app/phone/phone_plat/telephony_remote_party_information_api/group"/>
</component>
<component name="telephony_video_mailbox_settings_api" long-name="Telephony Video Mailbox Settings API" filter="s60" class="api">
<unit bldFile="/sf/app/phone/phone_plat/telephony_video_mailbox_settings_api/group"/>
</component>
<component name="telephony_configuration_api" long-name="Telephony Configuration API" filter="s60" class="api">
<unit bldFile="/sf/app/phone/phone_plat/telephony_configuration_api/group"/>
</component>
<component name="telephony_microphone_mute_status_api" long-name="Telephony Microphone Mute Status API" filter="s60" class="api">
<unit bldFile="/sf/app/phone/phone_plat/telephony_microphone_mute_status_api/group"/>
</component>
<component name="dialer_keypad_api" long-name="Dialer Keypad API" filter="s60" class="api">
<unit bldFile="/sf/app/phone/phone_plat/dialer_keypad_api/group"/>
</component>
<component name="telephony_logging_extension_api" long-name="Telephony Logging Extension API" filter="s60" class="api">
<unit bldFile="/sf/app/phone/phone_plat/telephony_logging_extension_api/group"/>
</component>
<component name="telephony_matching_extension_api" long-name="Telephony Matching Extension API" filter="s60" class="api">
<unit bldFile="/sf/app/phone/phone_plat/telephony_matching_extension_api/group"/>
</component>
<component name="telephony_bubble_extension_api" long-name="Telephony Bubble Extension API" filter="s60" class="api">
<unit bldFile="/sf/app/phone/phone_plat/telephony_bubble_extension_api/group"/>
</component>
<component name="telephony_menu_extension_api" long-name="Telephony Menu Extension API" filter="s60" class="api">
<unit bldFile="/sf/app/phone/phone_plat/telephony_menu_extension_api/group"/>
</component>
<component name="phone_application_commands_api" long-name="Phone Application Commands API" filter="s60" class="api">
<unit bldFile="/sf/app/phone/phone_plat/phone_application_commands_api/group"/>
</component>
<component name="phone_application_voip_commands_api" long-name="Phone Application VOIP Commands API" filter="s60" class="api">
<unit bldFile="/sf/app/phone/phone_plat/phone_application_voip_commands_api/group"/>
</component>
<component name="phone_telephony_mediator_api" long-name="Telephony Mediator API" filter="s60" class="api">
<unit bldFile="/sf/app/phone/phone_plat/telephony_mediator_api/group"/>
</component>
<component name="video_telephony_mediator_api" long-name="Video Telephony Mediator API" filter="s60" class="api">
<unit bldFile="/sf/app/phone/phone_plat/video_telephony_mediator_api/group"/>
</component>
</collection>
<collection name="phoneapp" long-name="Phone Application" level="app">
<component name="blacklist" filter="s60" long-name="Phone Blacklist Clearing" plugin="Y">
<unit bldFile="/sf/app/phone/phoneapp/blacklist/group"/>
</component>
<component name="phoneui" filter="s60" long-name="Phone UI">
<unit bldFile="/sf/app/phone/phoneapp/phoneui/group" filter="!test"/>
</component>
<component name="phoneuicontrol" filter="s60" long-name="Phone UI Control">
<unit bldFile="/sf/app/phone/phoneapp/phoneuicontrol/group"/>
</component>
<component name="phoneuistates" filter="s60" long-name="Phone UI States">
<unit bldFile="/sf/app/phone/phoneapp/phoneuistates/group"/>
</component>
<component name="phoneuiutils" filter="s60" long-name="Phone UI Utils">
<unit bldFile="/sf/app/phone/phoneapp/phoneuiutils/group"/>
</component>
<component name="phoneuiview" filter="s60" long-name="Phone UI View">
<unit bldFile="/sf/app/phone/phoneapp/phoneuiview/group"/>
</component>
<component name="phoneuivoipextension" filter="s60" long-name="Phone UI VOIP Extension">
<unit bldFile="/sf/app/phone/phoneapp/phoneuivoipextension/group"/>
</component>
<component name="silenceactionplugin" filter="s60" long-name="Silence Action Plugin" plugin="Y">
<unit bldFile="/sf/app/phone/phoneapp/silenceactionplugin/group"/>
</component>
<component name="phonemediatorcenter" filter="s60" long-name="Phone Mediator Center">
<unit bldFile="/sf/app/phone/phoneapp/phonemediatorcenter/group"/>
</component>
</collection>
<collection name="phoneengine" long-name="Phone Engine" level="engine">
<component name="phonecntfinder" filter="s60" long-name="Phone Contact Finder">
<unit bldFile="/sf/app/phone/phoneengine/phonecntfinder/group"/>
</component>
<component name="audiohandling" filter="s60" long-name="Phone Audio Handling">
<unit bldFile="/sf/app/phone/phoneengine/audiohandling/group"/>
</component>
<component name="callhandling" filter="s60" long-name="Call Handling">
<unit bldFile="/sf/app/phone/phoneengine/callhandling/group"/>
</component>
<component name="contacthandling" filter="s60" long-name="Phone Contact Handling">
<unit bldFile="/sf/app/phone/phoneengine/contacthandling/group"/>
</component>
<component name="loghandling" filter="s60" long-name="Phone Log Handling">
<unit bldFile="/sf/app/phone/phoneengine/loghandling/group"/>
</component>
<component name="engineinfo" filter="s60" long-name="Phone Engine Info">
<unit bldFile="/sf/app/phone/phoneengine/engineinfo/group"/>
</component>
<component name="phonemodel" filter="s60" long-name="Phone Model">
<unit bldFile="/sf/app/phone/phoneengine/phonemodel/group"/>
</component>
<component name="servicehandling" filter="s60" long-name="Phone Service Handling">
<unit bldFile="/sf/app/phone/phoneengine/servicehandling/group"/>
</component>
</collection>
<collection name="phonesettings" long-name="Phone Settings" level="plugin">
<component name="aiwcallimageplugin" filter="s60" long-name="Call Image AIW Plugin" plugin="Y">
<unit bldFile="/sf/app/phone/phonesettings/aiwcallimageplugin/group"/>
</component>
<component name="pslncallimageplugin" filter="s60" long-name="Call Image Personalization Plugin" plugin="Y">
<unit bldFile="/sf/app/phone/phonesettings/pslncallimageplugin/group"/>
</component>
</collection>
<collection name="phoneuis" long-name="Phone UIs" level="ui">
<component name="dialer" filter="s60" long-name="Dialer">
<unit bldFile="/sf/app/phone/phoneuis/dialer/group" filter="!test"/>
</component>
<component name="easydialing" filter="s60" long-name="Easy Dialing Plugin" introduced="^3" plugin="Y">
<unit bldFile="/sf/app/phone/phoneuis/easydialing/group"/>
</component>
<component name="bubblemanager" filter="s60" long-name="Phone Bubble Manager">
<unit bldFile="/sf/app/phone/phoneuis/bubblemanager/group"/>
</component>
<component name="connectutil" filter="s60" long-name="Connection Utility" plugin="Y">
<unit bldFile="/sf/app/phone/phoneuis/connectutil/group"/>
</component>
<component name="ussd" filter="s60" long-name="Unstructured Supplementary Services Data">
<unit bldFile="/sf/app/phone/phoneuis/ussd/group"/>
</component>
<component name="vmbx" filter="s60" long-name="Voice Mailbox">
<unit bldFile="/sf/app/phone/phoneuis/vmbx/group"/>
</component>
<component name="telephonydevicemode" filter="s60" long-name="Telephony Device Mode">
<unit bldFile="/sf/app/phone/phoneuis/telephonydevicemode/group"/>
</component>
</collection>
<collection name="phoneplugins" long-name="Phone Plugins" level="plugin">
<component name="telbranding" filter="s60" long-name="Tel Branding" introduced="^2" plugin="Y">
<unit bldFile="/sf/app/phone/phoneplugins/telbranding/group"/>
</component>
</collection>
</block>
  </layer>
 </systemModel>
</SystemDefinition>