<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SystemDefinition [
<!ELEMENT SystemDefinition ( systemModel )>
<!ATTLIST SystemDefinition
  name CDATA #REQUIRED
  schema CDATA #REQUIRED
>
<!-- all paths are relative to the environment variable specified by the root attribute, or SOURCEROOT if not.  -->

<!-- System Model Section of DTD -->
<!ELEMENT systemModel (layer+)>

<!ELEMENT layer (block* | collection*)*>
<!-- Kernel Services, Base Services, OS Services, Etc -->
<!ATTLIST layer
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
  levels NMTOKENS #IMPLIED
  span CDATA #IMPLIED
>

<!ELEMENT block (subblock* | collection*)*>
 <!-- Generic OS services, Comms Services, etc -->
<!ATTLIST block
  levels NMTOKENS #IMPLIED
  span CDATA #IMPLIED
  level NMTOKEN #IMPLIED
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
>

<!ELEMENT subblock (collection)*>
<!-- Cellular Baseband Services, Networking Services, etc -->
<!ATTLIST subblock
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
>

<!ELEMENT collection (component)*>
<!-- Screen Driver, Content Handling, etc -->
<!ATTLIST collection
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
  level NMTOKEN #IMPLIED
>

<!ELEMENT component (unit)*>
<!-- contains units or is a  package or prebuilt -->
<!ATTLIST component
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
  deprecated CDATA #IMPLIED
  introduced CDATA #IMPLIED
  contract CDATA #IMPLIED
  plugin (Y|N) "N"
  filter CDATA #IMPLIED
  class NMTOKENS #IMPLIED
  supports CDATA #IMPLIED
  purpose ( optional | mandatory | development ) "optional"
>

<!ELEMENT unit EMPTY >
<!-- must be buildable (bld.inf) -->
<!-- bldFile  may someday be removed in favour of mrp -->
<!ATTLIST unit
  mrp CDATA #IMPLIED
  filter CDATA #IMPLIED
  bldFile CDATA #IMPLIED
  root CDATA #IMPLIED
  version NMTOKEN #IMPLIED
  prebuilt NMTOKEN #IMPLIED
  late (Y|N) #IMPLIED
  priority CDATA #IMPLIED
>
]>
<SystemDefinition name="Symbian^4" schema="2.0.1">
  <systemModel>
    <layer name="mw" long-name="Middleware" levels="generic specific">
      <block name="ipappprotocols" level="generic" long-name="IP App Protocols" levels="plugin conn server if">
        <collection name="ipappprotocols_plat" long-name="IP App Protocols Platform Interfaces" level="if">
          <component name="srtp_api" long-name="SRTP API" filter="s60" class="api">
            <unit bldFile="/sf/mw/ipappprotocols/ipappprotocols_plat/srtp_api/group"/>
          </component>
          <component name="rtprtcp_api" long-name="RTP/RTCP API" filter="s60" class="api">
            <unit bldFile="/sf/mw/ipappprotocols/ipappprotocols_plat/rtprtcp_api/group"/>
          </component>
        </collection>
        <collection name="rtp" long-name="RTP" level="server">
          <component name="srtpstack" filter="s60" long-name="SRTP Stack">
            <unit bldFile="/sf/mw/ipappprotocols/rtp/srtpstack/group"/>
          </component>
          <component name="rtpstack" filter="s60" long-name="RTP Stack">
            <unit bldFile="/sf/mw/ipappprotocols/rtp/rtpstack/group"/>
          </component>
        </collection>
        <collection name="realtimenetprots" long-name="Real Time Net Protocols" level="server">
          <component name="symrtp" long-name="RTP" introduced="9.0" purpose="optional">
            <!-- Real Time Data Protocol -->
            <unit bldFile="/sf/mw/ipappprotocols/realtimenetprots/rtp/group" mrp="/sf/mw/ipappprotocols/realtimenetprots/rtp/group/mm-protocols_rtp.mrp"/>
          </component>
          <component name="srtp" long-name="Secure RTP" introduced="^4" purpose="optional">
            <unit bldFile="/sf/mw/ipappprotocols/realtimenetprots/srtp/group" mrp="/sf/mw/ipappprotocols/realtimenetprots/srtp/group/mm-protocols_srtp.mrp"/>
          </component>
          <component name="sipfw" long-name="SIP Framework" introduced="9.2" purpose="optional">
            <unit bldFile="/sf/mw/ipappprotocols/realtimenetprots/sipfw/Group" mrp="/sf/mw/ipappprotocols/realtimenetprots/sipfw/Group/mm-protocols_SIP2_Com.mrp" version="2"/>
          </component>
        </collection>
        <collection name="sipplugins" long-name="SIP Plugins" level="plugin">
          <component name="sippwlanplugin" filter="s60" long-name="SIP WLAN Plugin" plugin="Y">
            <unit bldFile="/sf/mw/ipappprotocols/sipplugins/sippwlanplugin/group"/>
          </component>
          <component name="sippsipsettingsui" filter="s60" long-name="SIP Settings UI" plugin="Y">
            <unit bldFile="/sf/mw/ipappprotocols/sipplugins/sippsipsettingsui/group"/>
          </component>
          <component name="sippdevmgmtsipadapter" filter="s60" long-name="Device Management SIP Settings Adapter" plugin="Y">
            <unit bldFile="/sf/mw/ipappprotocols/sipplugins/sippdevmgmtsipadapter/group"/>
          </component>
          <component name="sippsystemstatemonitor" filter="s60" long-name="SIP System State Monitor" plugin="Y">
            <unit bldFile="/sf/mw/ipappprotocols/sipplugins/sippsystemstatemonitor/group"/>
          </component>
          <component name="sippsipadapter" filter="s60" long-name="SIP Adapter" introduced="^3" plugin="Y">
            <unit bldFile="/sf/mw/ipappprotocols/sipplugins/sippsipadapter/group"/>
          </component>
        </collection>
        <collection name="sipproviderplugins" long-name="SIP Provider Plugins" level="conn">
          <component name="sipprovider" long-name="SIP Provider" introduced="^2" purpose="optional" plugin="Y">
            <unit bldFile="/sf/mw/ipappprotocols/sipproviderplugins/sipprovider/group" mrp="/sf/mw/ipappprotocols/sipproviderplugins/sipprovider/group/mm-protocols_SipProvider.mrp"/>
          </component>
        </collection>
        <collection name="ipappprotocols_info" long-name="IP App Protocols Info" level="if">
          <component name="ipappprotocols_metadata" long-name="IP App Protocols Metadata" introduced="^2" purpose="development" class="config PC">
            <unit mrp="/sf/mw/ipappprotocols/ipappprotocols_info/ipappprotocols_metadata/ipappprotocols_metadata.mrp"/>
          </component>
        </collection>
      </block>
    </layer>
  </systemModel>
</SystemDefinition>
