<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SystemDefinition [
<!ELEMENT SystemDefinition ( systemModel )>
<!ATTLIST SystemDefinition
  name CDATA #REQUIRED
  schema CDATA #REQUIRED
>
<!-- all paths are relative to the environment variable specified by the root attribute, or SOURCEROOT if not.  -->

<!-- System Model Section of DTD -->
<!ELEMENT systemModel (layer+)>

<!ELEMENT layer (block* | collection*)*>
<!-- Kernel Services, Base Services, OS Services, Etc -->
<!ATTLIST layer
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
  levels NMTOKENS #IMPLIED
  span CDATA #IMPLIED
>

<!ELEMENT block (subblock* | collection*)*>
 <!-- Generic OS services, Comms Services, etc -->
<!ATTLIST block
  levels NMTOKENS #IMPLIED
  span CDATA #IMPLIED
  level NMTOKEN #IMPLIED
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
>

<!ELEMENT subblock (collection)*>
<!-- Cellular Baseband Services, Networking Services, etc -->
<!ATTLIST subblock
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
>

<!ELEMENT collection (component)*>
<!-- Screen Driver, Content Handling, etc -->
<!ATTLIST collection
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
  level NMTOKEN #IMPLIED
>

<!ELEMENT component (unit)*>
<!-- contains units or is a  package or prebuilt -->
<!ATTLIST component
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
  deprecated CDATA #IMPLIED
  introduced CDATA #IMPLIED
  contract CDATA #IMPLIED
  plugin (Y|N) "N"
  filter CDATA #IMPLIED
  class NMTOKENS #IMPLIED
  supports CDATA #IMPLIED
  purpose ( optional | mandatory | development ) "optional"
>

<!ELEMENT unit EMPTY >
<!-- must be buildable (bld.inf) -->
<!-- bldFile  may someday be removed in favour of mrp -->
<!ATTLIST unit
  mrp CDATA #IMPLIED
  filter CDATA #IMPLIED
  bldFile CDATA #IMPLIED
  root CDATA #IMPLIED
  version NMTOKEN #IMPLIED
  prebuilt NMTOKEN #IMPLIED
  late (Y|N) #IMPLIED
  priority CDATA #IMPLIED
>
]>
<SystemDefinition name="Symbian^3" schema="2.0.1">
  <systemModel>
    <layer name="mw" long-name="Middleware" levels="generic specific">
      <block name="btservices" level="generic" long-name="Bluetooth Services" levels="framework server generic specific plugin">
        <collection name="bluetoothengine" long-name="Bluetooth Engine" level="framework">
          <component name="bteng" filter="s60" long-name="Bluetooth Engine">
            <unit bldFile="/sf/mw/btservices/bluetoothengine/bteng/group"/>
          </component>
          <component name="btnotif" filter="s60" long-name="Bluetooth Notifier">
            <unit bldFile="/sf/mw/btservices/bluetoothengine/btnotif/group"/>
          </component>
          <component name="btaudioman" filter="s60" long-name="Bluetooth Audio Manager">
            <unit bldFile="/sf/mw/btservices/bluetoothengine/btaudioman/group"/>
          </component>
          <component name="btmac" filter="s60" long-name="Bluetooth Mono Audio Controller" plugin="Y">
            <unit bldFile="/sf/mw/btservices/bluetoothengine/btmac/group"/>
          </component>
          <component name="btsac" filter="s60" long-name="Bluetooth Stereo Audio Controller" plugin="Y">
            <unit bldFile="/sf/mw/btservices/bluetoothengine/btsac/group"/>
          </component>
          <component name="btaudiostreamer" filter="s60" long-name="Bluetooth Audio Streamer">
            <unit bldFile="/sf/mw/btservices/bluetoothengine/btaudiostreamer/group"/>
          </component>
          <component name="btsap" filter="s60" long-name="Bluetooth SIM Access Profile" plugin="Y">
            <unit bldFile="/sf/mw/btservices/bluetoothengine/btsap/group"/>
          </component>
          <component name="btui" filter="s60" long-name="Bluetooth UI">
            <unit bldFile="/sf/mw/btservices/bluetoothengine/btui/group"/>
          </component>
          <component name="btpbap" filter="s60" long-name="Bluetooth Phonebook Access Profile" plugin="Y">
            <unit bldFile="/sf/mw/btservices/bluetoothengine/btpbap/group"/>
          </component>
          <component name="bthid" filter="s60" long-name="Bluetooth HID">
            <unit bldFile="/sf/mw/btservices/bluetoothengine/bthid/group"/>
          </component>
          <component name="btctrldcmoadapter" filter="s60" long-name="Bluetooth Control DCMO Adapter" introduced="^3" plugin="Y">
            <unit bldFile="/sf/mw/btservices/bluetoothengine/btctrldcmoadapter/group"/>
          </component>
        </collection>
        <collection name="bluetoothappprofiles" long-name="Bluetooth Application Profiles" level="plugin">
          <component name="avrcp" long-name="Bluetooth AVRCP" introduced="9.1" purpose="optional">
            <unit bldFile="/sf/mw/btservices/bluetoothappprofiles/avrcp" mrp="/sf/mw/btservices/bluetoothappprofiles/avrcp/bluetooth_avrcp.mrp"/>
          </component>
        </collection>
        <collection name="btservices_info" long-name="BT Services Info" level="plugin">
          <component name="btservices_plat" filter="s60" long-name="BT Services Platform Interfaces" class="api">
            <unit bldFile="/sf/mw/btservices/btservices_plat/group"/>
          </component>
          <component name="btservices_pub" filter="s60" long-name="BT Services Public Interfaces" class="api">
            <unit bldFile="/sf/mw/btservices/btservices_pub/group"/>
          </component>
          <component name="btservices_metadata" long-name="BT Services Metadata" introduced="^3" purpose="development" class="config PC">
            <unit mrp="/sf/mw/btservices/btservices_info/btservices_metadata/btservices_metadata.mrp"/>
          </component>
          <component name="btservices_api_test" long-name="BT Services API Tests" purpose="development" filter="s60,test,api_test">
            <unit/>
          </component>
        </collection>
      </block>
    </layer>
  </systemModel>
</SystemDefinition>
